version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db_dll
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: dll
      MYSQL_USER: dll_user
      MYSQL_PASSWORD: covid19
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: