swagger: "2.0"
info:
  description: "Ceci est la documentation du serveur DLL Cas Contact."
  version: "1.0.0"
  title: "Swagger DLL Cas Contact"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "meddouri.badis@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:4040"
tags:
  - name: "classe"
    description: "Les opérations utilisateurs"
    externalDocs:
      description: "Découvrez notre interface graphique"
      url: "http://localhost:8080"
schemes:
  - "https"
  - "http"
paths:
  /classes/:
    post:
      tags:
        - "classes"
      summary: "Créer un classes"
      
      operationId: "register"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        default:
  
  /classes:
    get:
      tags:
        - "classes"
      summary: "Recuperer les classes"
      
      operationId: "getAll"
      produces:
        - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /classes/liste:
    get:
      tags:
        - "classes"
      summary: "Récupérer la liste"
      description: ""
      operationId: "getListe"
      produces:
        - "application/json"
      parameters: []
      responses:
        default:
          schema:
            $ref: "#/definitions/User"
          description: "successful operation"
  /classes/{id}:
    get:
      tags:
        - "classes"
      summary: "Récuperer une classes par son identifiant"
      description: ""
      operationId: "getClassesById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "The name that needs to be fetched. Use 1 for testing. "
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Classes"
        "400":
          description: "ID fourni invalide"
        "404":
          description: "Classes non trouvé"
    put:
      tags:
        - "classes"
      summary: "Mettre à jour la classes"
      description: ""
      operationId: "updateClasses"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of Classeroom that need to be updated"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Objet utilisateur à mettre à jour"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "400":
          description: "ID fourni invalide"
        "404":
          description: "Utilisateur non trouvé"
    delete:
      tags:
        - "user"
      summary: "Supprimer un utilisateur"
      description: "Ne peut être réalisé que par un administrateur ou un profeesseur."
      operationId: "deleteUser"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of user that needs to be deleted"
          required: true
          type: "string"
      responses:
        "400":
          description: "ID fourni invalide"
        "404":
          description: "Utilisateur non trouvé"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      numEtud:
        type: "string"
      id_classe:
        type: "string"
    xml:
      name: "User"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
