swagger: "2.0"
info:
  description: "Ceci est la documentation du serveur DLL Cas Contact."
  version: "1.0.0"
  title: "Swagger DLL Cas Contact"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "meddouri.badis@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:4040"
tags:
  - name: "mail"
    description: "Les opérations utilisateurs"
    externalDocs:
      description: "Découvrez notre interface graphique"
      url: "http://localhost:8080"
schemes:
  - "https"
  - "http"
paths:
  
  /mail:
    put:
      tags:
        - "mail"
      summary: " Envoyer un mail"
      description: ""
      operationId: "sendMail"
      produces:
        - "application/json"
      responses:

        "404":
          description: "Mail non trouvé"
  
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Mail:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      mailname:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      numEtud:
        type: "string"
 
    xml:
      name: "mail"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
